"""add project analysis tracking

Revision ID: 708302e066a8
Revises: 8cc25e5c450b
Create Date: 2026-10-06 23:15:14.185808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708302e066a8'
down_revision: Union[str, Sequence[str], None] = '8cc25e5c450b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('parent_analysis_id', sa.Integer(), nullable=True),
    sa.Column('analysis_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('files_scanned', sa.Integer(), server_default='0', nullable=False),
    sa.Column('files_parsed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('files_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unsupported_files', sa.Integer(), server_default='0', nullable=False),
    sa.Column('parse_errors', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_analysis_id'], ['project_analysis.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_analysis_commit_sha'), 'project_analysis', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_project_analysis_id'), 'project_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_project_analysis_parent_analysis_id'), 'project_analysis', ['parent_analysis_id'], unique=False)
    op.create_index('ix_project_analysis_project_commit', 'project_analysis', ['project_id', 'commit_sha'], unique=False)
    op.create_index(op.f('ix_project_analysis_project_id'), 'project_analysis', ['project_id'], unique=False)
    op.create_index('ix_project_analysis_project_number', 'project_analysis', ['project_id', 'analysis_number'], unique=False)
    op.create_index(op.f('ix_project_analysis_status'), 'project_analysis', ['status'], unique=False)
    op.create_table('analysis_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('lines', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bytes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('parse_status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['project_analysis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_files_analysis_id'), 'analysis_files', ['analysis_id'], unique=False)
    op.create_index('ix_analysis_files_analysis_path', 'analysis_files', ['analysis_id', 'file_path'], unique=False)
    op.create_index(op.f('ix_analysis_files_id'), 'analysis_files', ['id'], unique=False)
    op.create_table('analysis_language_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('files', sa.Integer(), server_default='0', nullable=False),
    sa.Column('parsed_files', sa.Integer(), server_default='0', nullable=False),
    sa.Column('parse_errors', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lines', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bytes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['project_analysis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_language_analysis_language', 'analysis_language_statistics', ['analysis_id', 'language'], unique=False)
    op.create_index(op.f('ix_analysis_language_statistics_analysis_id'), 'analysis_language_statistics', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_language_statistics_id'), 'analysis_language_statistics', ['id'], unique=False)
    op.add_column('projects', sa.Column('current_analysis_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_projects_current_analysis_id'), 'projects', ['current_analysis_id'], unique=False)
    op.create_foreign_key('fk_projects_current_analysis', 'projects', 'project_analysis', ['current_analysis_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_projects_current_analysis', 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_current_analysis_id'), table_name='projects')
    op.drop_column('projects', 'current_analysis_id')
    op.drop_index(op.f('ix_analysis_language_statistics_id'), table_name='analysis_language_statistics')
    op.drop_index(op.f('ix_analysis_language_statistics_analysis_id'), table_name='analysis_language_statistics')
    op.drop_index('ix_analysis_language_analysis_language', table_name='analysis_language_statistics')
    op.drop_table('analysis_language_statistics')
    op.drop_index(op.f('ix_analysis_files_id'), table_name='analysis_files')
    op.drop_index('ix_analysis_files_analysis_path', table_name='analysis_files')
    op.drop_index(op.f('ix_analysis_files_analysis_id'), table_name='analysis_files')
    op.drop_table('analysis_files')
    op.drop_index(op.f('ix_project_analysis_status'), table_name='project_analysis')
    op.drop_index('ix_project_analysis_project_number', table_name='project_analysis')
    op.drop_index(op.f('ix_project_analysis_project_id'), table_name='project_analysis')
    op.drop_index('ix_project_analysis_project_commit', table_name='project_analysis')
    op.drop_index(op.f('ix_project_analysis_parent_analysis_id'), table_name='project_analysis')
    op.drop_index(op.f('ix_project_analysis_id'), table_name='project_analysis')
    op.drop_index(op.f('ix_project_analysis_commit_sha'), table_name='project_analysis')
    op.drop_table('project_analysis')
    # ### end Alembic commands ###
