"""add github activity timestamp

Revision ID: 8cc25e5c450b
Revises: 552edbdafa1b
Create Date: 2026-10-05 16:06:57.134610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc25e5c450b'
down_revision: Union[str, Sequence[str], None] = '552edbdafa1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_repositories', sa.Column('last_github_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_github_repositories_last_github_activity_at'), 'github_repositories', ['last_github_activity_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_repositories_last_github_activity_at'), table_name='github_repositories')
    op.drop_column('github_repositories', 'last_github_activity_at')
    # ### end Alembic commands ###
