"""create github repositories

Revision ID: b396080f4590
Revises: 1a4635f675bf
Create Date: 2026-10-03 14:48:48.349396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b396080f4590'
down_revision: Union[str, Sequence[str], None] = '1a4635f675bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_repo_id', sa.BigInteger(), nullable=False),
    sa.Column('github_installation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('owner_login', sa.String(length=255), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('html_url', sa.String(length=1024), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['github_installation_id'], ['github_installations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_repositories_github_installation_id'), 'github_repositories', ['github_installation_id'], unique=False)
    op.create_index(op.f('ix_github_repositories_github_repo_id'), 'github_repositories', ['github_repo_id'], unique=True)
    op.create_index(op.f('ix_github_repositories_id'), 'github_repositories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_repositories_id'), table_name='github_repositories')
    op.drop_index(op.f('ix_github_repositories_github_repo_id'), table_name='github_repositories')
    op.drop_index(op.f('ix_github_repositories_github_installation_id'), table_name='github_repositories')
    op.drop_table('github_repositories')
    # ### end Alembic commands ###
